### ISSUE TITLE
Feature Request: Search and Find function

### ISSUE THREAD

**Issue by RandomLegend** [pf-wikis/mapping#210]
Heyho!

awesome map!

Might i add the wish to build a search and find function? It's really hard to find places by hand if you don't know exactly where they are.

Thanks for project!

**Comment by oznogon** [comment]
Right now the best search is PathfinderWiki itself. Most locations already have wiki articles that contain embedded maps from this project, and you can right-click/two-finger tap the embedded map to open it in the full map as a new tab.

For instance, if I [search the wiki](https://pathfinderwiki.com/w/index.php?search=Hanging+City&title=Special%3ASearch&wprov=acrw1) for "Hanging City", the [Hanging City of Teskra](https://pathfinderwiki.com/wiki/Hanging_City_of_Teskra) article is the first result and contains an embedded map. I can right-click that map to [open the full map at its location](https://map.pathfinderwiki.com/#location=7/26.411/-21.478).

Adding a search element in the Mapbox GL viewer is less straightforward than it might seem. Mapbox is designed for Earth and most of its supported search interfaces poll APIs containing Earth data. That's not useful for Golarion. Any search functionality would need to use our data instead.

It might be possible to build a search on something like [`QuerySourceFeatures`](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#querysourcefeatures) ([non-search example](https://docs.mapbox.com/mapbox-gl-js/example/query-similar-features/)), but at a quick glance I don't see anything we can easily plug in for our purposes, and we'd have to implement some search functionality like autocomplete and fuzzy matching ourselves.
