### ISSUE TITLE
map.pathfinderwiki.com is not discoverable to wiki visitors

### ISSUE THREAD

**Issue by oznogon** [pf-wikis/mapping#297]
A quick review of mentions of this map on Reddit and Discord suggests that many users don't know that https://map.pathfinderwiki.com exists. These users interact with the map entirely and solely through the small embeds on pathfinderwiki.com.

Some of the discoverability problems:

- The `RightClickMenu` control to open in a new tab is hidden to users, especially on mobile.
- There is no way to expand the embedded map view to a larger view without accessing the "Open in New Tab" control in the `RightClickMenu`.
- map.pathfinderwiki.com isn't linked to from the map's `Attribution` control, or the wiki's [Widget:Map](https://pathfinderwiki.com/wiki/Widget:Map) or [Template:DisplayMap](https://pathfinderwiki.com/wiki/Template:DisplayMap).

The only uses of the embedded map that link to map.pathfinderwiki.com are on [Portal:Geography](https://pathfinderwiki.com/wiki/Portal:Geography), the [Template:DisplayMap](https://pathfinderwiki.com/wiki/Template:DisplayMap) documentation, and uses of [Template:Location of Interest](https://pathfinderwiki.com/wiki/Template:Location_of_Interest) on [PathfinderWiki:Map Locations Without Articles](https://pathfinderwiki.com/wiki/PathfinderWiki:Map_Locations_Without_Articles). 

#295 attempts to address this by adding the MapLibre-GL `FullscreenControl` button to embedded uses of the map. This still doesn't improve discoverability of map.pathfinderwiki.com, but at least mitigates the lack of usability when limited to an embed.

If this isn't a desired solution, other suggestions include:

- editing Widget:Map or Template:DisplayMap to include a link to the map at the given coordinates
- modifying the embedded map's Attribution control to include a link to map.pathfinderwiki.com
- creating a custom button control to open the embed's current view in a new tab, replacing the `RightClickMenu` "Open in new tab" control

**Comment by manuel-hegner** [comment]
You make a great point. Thank you for thinking about these kinds of things.

I would prefer a custom control (with the same icon) that opens another tab, as I think that makes the webpage in and of itself more discoverable.  And we should decide if to include this based on the existing embedded parameter. What do you think?

We might also think about making a foundry module that makes including the map in journals easy. Though I think most people would want to use it as a level, which is not really possible without a lot of work.

**Comment by oznogon** [comment]
> And we should decide if to include this based on the existing embedded parameter. What do you think?

I think it makes the most sense to show the control only on embedded uses. People already on map.pathfinderwiki.com are IMO less likely to need a custom control to open a new window or resize the map view.

> We might also think about making a foundry module that makes including the map in journals easy.

The Foundry add-on [Embed Cloud Documents](https://foundryvtt.com/packages/embeds) supports adding iframes with arbitrary URLs to journals. We could write a guide for using that plugin to embed our map.

The add-on itself isn't open source, but its method is trivial (writing HTML as a parameterized string, with a function to populate the `iframe` attributes and URL parameters upon creation) and could be adapted to be tailored for the wiki map.

**Comment by manuel-hegner** [comment]
I have pushed a solution using the normal button component but opening the map in a new tab. What do you think?

**Comment by oznogon** [comment]
Looks and works great for me!

**Comment by manuel-hegner** [comment]
Nice
