### ISSUE TITLE
Source credits

### ISSUE THREAD

**Issue by oznogon** [pf-wikis/mapping#42]
Hi, Manuel (and Robert)! Thank you for picking up and moving this work forward.

It'd be great to have [my past work](https://oznogon.com/golarion/) (and John Mechalas's work that it was based on), which appears to have been imported into this project, credited. Looks like a lot of geometry, the color palette, and some of the non-geometry content was pulled in from that work with few or no changes.

Thanks!

**Comment by manuel-hegner** [comment]
This will be done of course. I am on vacation right now and write something after that.
