### ISSUE TITLE
Import issue: Missing rasters

### ISSUE THREAD

**Issue by RDomiano** [pf-wikis/mapping#77]
Hello,
It looks like the folder for your sources is missing some data. The images subfolder leads to a 404 and is missing all the label, raster, and other data that was within it. Would it be possible to have access to those? I'd love to look around and play with what you all have compiled.

**Comment by manuel-hegner** [comment]
That is by design. We can not publish the image sources because they are copyrighted material. Only core contributors can gain access to the images.
